services:

  asmr-downloader:
    image: asmr-downloader:v1.0.2
    container_name: asmr-downloader
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DOWNLOAD_DIR: "/data/downloads"
      ASMR_API_HOST: "https://api.asmr-200.com"
    volumes:
      - ./downloads:/data/downloads